run:
  timeout: 5m
  go: "1.21"
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/kolosys/go-timecapsule
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - typecheck
    - goconst
    - gocyclo
    - misspell
    - unparam
    - gocritic
    - gosec
    - lll
    - prealloc
    - unused
    - gocognit
    - goprintffuncname
    - nakedret
    - noctx
    - paralleltest
    - tparallel
    - wastedassign
    - whitespace
    # - wrapcheck  # Disabled - too strict for this project

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - dupl
        - gocyclo
        - paralleltest
        - tparallel
    - path: example_test\.go
      linters:
        - gomnd
        - goconst
        - dupl
        - gocyclo
        - paralleltest
        - tparallel
    - path: cmd/demo/
      linters:
        - gomnd
        - goconst
        - dupl
        - gocyclo
        - paralleltest
        - tparallel
        - gosec
    - linters:
        - gosec
      text: "G101: Potential hardcoded credentials"
      source: "// nolint:gosec"
    - linters:
        - gosec
      text: "G204: Subprocess launched with variable"
      source: "// nolint:gosec"
    - linters:
        - gosec
      text: "G601: Implicit memory aliasing in for loop"
      source: "// nolint:gosec"

  max-issues-per-linter: 0
  max-same-issues: 0
